
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

const host = env("DB_HOST");
const user = env("DB_USER");
const password = env("DB_PASSWORD");
const database = env("DB_NAME");
const port = process.env.DB_PORT || "3306";

const url = `mysql://${user}:${encodeURIComponent(password)}@${host}:${port}/${database}`;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: url,
  },
});
