// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import path from "node:path";
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

const root = process.cwd();
config({ path: path.join(root, ".env") });
config({ path: path.join(root, ".env.production"), override: true });
config({ path: path.join(root, ".env.local"), override: true });
import { resolveDatabaseUrlOrPlaceholder } from "./lib/database-url";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node prisma/seed.mjs",
  },
  datasource: {
    url: resolveDatabaseUrlOrPlaceholder(),
  },
});
