/** Arabic UI strings for /admin (centralized). */
export const adminCopy = {
  sidebar: {
    workspaceTitle: "مساحة العمل",
    workspaceSubtitle: "إدارة المحتوى والأدوار والإعدادات من مكان واحد.",
    badgeLive: "مباشر",
    dashboardHome: "الرئيسية",
    magazines: "المجلات والإصدارات",
    researches: "بحوث المجلات",
    advisors: "المستشارون",
    approvals: "موافقات النشر",
    publicationFee: "رسوم النشر",
    transactions: "المعاملات",
    emails: "مركز البريد",
    content: "المحتوى",
    traffic: "تحليلات الزيارات",
    account: "أمان الحساب",
  },

  common: {
    loading: "جاري التحميل…",
    edit: "تعديل",
    delete: "حذف",
    cancel: "إلغاء",
    cancelEdit: "إلغاء التحرير",
    save: "حفظ",
    saving: "جاري الحفظ…",
    create: "إنشاء",
    update: "تحديث",
    remove: "إزالة",
    openLink: "فتح الرابط",
    openImage: "فتح الصورة",
    openFile: "فتح الملف",
    openPdf: "فتح ملف PDF",
    selectedFile: "الملف المحدد:",
    backToMagazines: "← العودة إلى المجلات",
    selectPlaceholder: "— اختر —",
    working: "جاري المعالجة…",
    yesDelete: "هل أنت متأكد؟",
    status: "الحالة:",
    iconLabel: "الأيقونة:",
    sortLabel: "الترتيب:",
    publicPage: "الصفحة العامة:",
    openInNewTab: "فتح في تبويب جديد",
  },

  dashboardHome: {
    title: "الرئيسية",
    explainer:
      "نقطة البداية في لوحة التحكم: انتقل إلى أي وحدة أدناه لإدارة المجلات، الأشخاص، الموافقات، البريد، المحتوى العام، أو إحصاءات الزيارات.",
    statusAria: "ملخص لوحة التحكم",
    coreModules: "الوحدات الأساسية",
    navCoverage: "اكتمال التنقل",
    currentMode: "وضع التشغيل",
    operational: "عادي",
    moduleMagazinesTitle: "المجلات والإصدارات",
    moduleMagazinesDesc: "إنشاء المجلات وتحديثها وإدارة الإصدارات والمرفقات.",
    moduleAdvisorsTitle: "المستشارون",
    moduleAdvisorsDesc: "إضافة مستشارين وتعديل بياناتهم وإزالتهم من القائمة العامة.",
    moduleApprovalsTitle: "موافقات النشر",
    moduleApprovalsDesc: "مراجعة طلبات النشر واعتمادها أو رفضها مع ملاحظات.",
    moduleEmailsTitle: "مركز البريد",
    moduleEmailsDesc: "إرسال رسائل تشغيلية أو تحريرية ومتابعة سجل الإرسال.",
    moduleContentTitle: "المحتوى",
    moduleContentDesc: "إدارة المدونات والمؤتمرات والمجالات المعروضة على الموقع.",
    moduleTrafficTitle: "تحليلات الزيارات",
    moduleTrafficDesc: "متابعة المشاهدات والتفاعلات لكل مجلة ضمن نطاق زمني.",
    openModule: "فتح الوحدة ←",
  },

  magazines: {
    pageTitle: "لوحة المجلات",
    /** Suspense fallback line under title */
    pageFallbackSubtitle: "جاري تحميل لوحة المجلات…",
    title: "لوحة المجلات",
    explainer:
      "من هنا تنشئ المجلات وتعدّلها، تربط المستشارين المعتمدين، وتضيف إصداراتًا مع ملفات PDF، ثم تنتقل لبحوث كل إصدار عند الحاجة.",
    overviewAria: "نظرة عامة على المجلات",
    totalMagazines: "عدد المجلات",
    totalVersions: "عدد الإصدارات",
    advisorOptions: "خيارات المستشارين",
    tabMagazines: "المجلات والإصدارات",
    tabResearches: "البحوث",
    tablistAria: "أقسام إدارة المجلات",
    sectionCreateMagazineExplainer:
      "أدخل بيانات المجلة والغلاف والملفات الاختيارية، ثم حدّد المستشارين المعتمدين قبل الحفظ.",
    editMagazine: (id: number) => `تعديل المجلة #${id}`,
    createMagazine: "مجلة جديدة",
    placeholderTitle: "اسم المجلة",
    placeholderDescription: "الوصف",
    placeholderCategory: "التصنيف",
    languageLabel: "لغة المجلة",
    languageAr: "العربية",
    languageEn: "English",
    listLanguageLabel: "اللغة:",
    bannerCurrent: "الغلاف الحالي:",
    bannerNoneEdit: "لا يوجد غلاف محفوظ؛ ارفع صورة أدناه.",
    bannerRequiredNew: "رفع غلاف مطلوب للمجلات الجديدة.",
    placeholderIssn: "ISSN",
    placeholderImpact: "معامل التأثير",
    placeholderCurrentVersion: "الإصدار الحالي",
    placeholderNextRelease: "تاريخ الإصدار القادم (حقل التاريخ)",
    pdfSelected: "ملف PDF المحدد:",
    pdfCurrent: "ملف PDF الحالي:",
    pdfNone: "لم يُرفع ملف PDF بعد.",
    placeholderPublicationPref: "تفضيلات النشر",
    placeholderVersionMessage: "رسالة الإصدار",
    placeholderCertification: "الاعتماد أو الشهادة",
    contactSectionTitle: "معلومات التواصل",
    contactSectionExplainer:
      "اختياري: اترك الحقول فارغة لعرض بيانات التواصل الافتراضية للموقع على صفحة المجلة.",
    placeholderContactPhone: "هاتف (عرض) — مثال: ٠٠٢ +١٠٦٦٢٢٣٣٩٩",
    placeholderContactPhoneTel: "هاتف (للاتصال — E.164، اختياري) — مثال: +201066223399",
    placeholderContactEmail: "البريد الإلكتروني",
    placeholderContactAddress: "العنوان",
    advisorSourceGlobal: "قائمة المستشارين العامة",
    advisorSourceAttached: "مستشارو هذه المجلة",
    advisorSourceAttachedDisabled: "(متاح أثناء التحرير)",
    advisorSourceBoth: "المصدران معًا",
    sectionApprovedAdvisorsExplainer:
      "حدّد المستشارين الذين تُعتمد آراؤهم لهذه المجلة؛ يظهر ذلك على الموقع حسب إعدادات العرض.",
    approvedAdvisorsTitle: "المستشارون المعتمدون",
    noAdvisorsEditing: "لا يوجد مستشارون ضمن المصدر المحدد.",
    noAdvisorsNew: "لا توجد مستشارون بعد. أضف مستشارين من صفحة المستشارين ثم ارجع للاختيار.",
    noApprovingYet: "لم يُحدد مستشارون معتمدون لهذه المجلة بعد.",
    selectedApprovals: "المعتمدون المحددون:",
    submitCreate: "إنشاء المجلة",
    submitUpdate: "تحديث المجلة",
    submitSaving: "جاري الحفظ…",
    cancelEdit: "إلغاء التحرير",
    confirmDeleteMagazine: "حذف هذه المجلة؟",
    sectionListExplainer: "ابحث عن مجلة، ثم افتح صفحة المستشارين أو شروط النشر أو حرّر أو احذف.",
    listTitle: "المجلات",
    searchMagazines: "بحث بالاسم…",
    issnLabel: "ISSN:",
    currentLabel: "الإصدار:",
    approvedCount: "معتمدون:",
    manageAdvisors: "إدارة المستشارين",
    publishingConditions: "شروط النشر",
    sectionVersionFormExplainer:
      "أنشئ إصدارًا جديدًا أو حدّث إصدارًا قائمًا مع تاريخ الإصدار وملف العد الاختياري.",
    editVersion: "تعديل الإصدار",
    createVersion: "إصدار جديد",
    selectMagazine: "اختر المجلة",
    placeholderVersionCode: "رقم أو اسم الإصدار",
    placeholderVersionTitle: "عنوان الإصدار",
    placeholderPageCount: "عدد الصفحات",
    versionPdfHint: "لا يوجد PDF لهذا الإصدار (اختياري).",
    versionPdfCurrent: "ملف العد الحالي:",
    placeholderNotes: "ملاحظات",
    submitVersionCreate: "إنشاء الإصدار",
    submitVersionUpdate: "تحديث الإصدار",
    confirmDeleteVersion: "حذف هذا الإصدار؟",
    sectionVersionsExplainer: "جميع الإصدارات؛ انتقل لإدارة بحوث إصدار معيّن أو حرّر البيانات.",
    versionsTitle: "الإصدارات",
    searchVersions: "بحث باسم المجلة أو رقم الإصدار…",
    magazineFallback: (id: number) => `مجلة #${id}`,
    manageResearches: "إدارة البحوث",
    ariaMagazinePicker: "المجلة للبحوث",
    ariaVersionPicker: "الإصدار للبحوث",
  },

  researchesPage: {
    title: "بحوث المجلات",
    explainer:
      "حرّر أسماء الباحثين والعناوين والروابط والملخصات وترتيب العرض لكل إصدار مجلة؛ التغييرات تنعكس على الصفحة العامة للإصدار.",
    loadingEditor: "جاري تحميل المحرّر…",
  },

  advisorsPage: {
    title: "إدارة المستشارين",
    explainer:
      "أضف أعضاء اللجان في القائمة أدناه، واختر من يظهر على صفحة اللجنة الاستشارية العامة؛ ثم اربط المستشارين بالمجلات من لوحة المجلات.",
    sectionFormExplainer: "املأ الاسم والمنصب ورفع صورة اختيارية وسيرة مختصرة ثم احفظ.",
    editAdvisor: "تعديل مستشار",
    addAdvisor: "إضافة مستشار",
    placeholderName: "الاسم",
    placeholderTitle: "المسمّى الوظيفي أو الانتماء",
    placeholderBio: "نبذة (اختياري)",
    photoSelected: "الصورة المحددة:",
    photoCurrent: "الصورة الحالية:",
    photoNone: "لم تُرفع صورة بعد.",
    confirmDelete: "حذف هذا المستشار؟",
    listExplainer: "قائمة جميع المستشارين المتاحين ربطهم بالمجلات.",
    listSectionTitle: "جميع المستشارين",
    committeeDisplayTitle: "المعروضون على صفحة اللجنة الاستشارية",
    committeeDisplayExplainer:
      "حدّد المستشارين الذين يظهرون للزوار في صفحة اللجنة الاستشارية العامة. الترتيب يتبع ترتيب التحديد.",
    committeeDisplayEmpty: "لا يوجد مستشارون في القائمة بعد. أضف مستشاراً أولاً.",
    saveCommitteeDisplay: "حفظ العرض على الموقع",
    featuredBadge: "معروض على الموقع",
  },

  approvalsPage: {
    title: "موافقات النشر",
    explainer:
      "اطّلع على طلبات النشر المرسلة من الباحثين، أضف ملاحظات المراجعة، ثم اعتمد الطلب أو ارفضه.",
    empty: "لا توجد طلبات.",
    placeholderNotes: "ملاحظات المراجعة",
    approve: "اعتماد",
    reject: "رفض",
    statusAwaitingPayment: "بانتظار الدفع",
    statusPending: "قيد المراجعة",
    statusApproved: "معتمد",
    statusRejected: "مرفوض",
    statusLabel: "الحالة:",
    paymentLabel: "الدفع:",
    paymentCompleted: "مدفوع",
    paymentRefunded: "مسترد",
    paymentPending: "غير مكتمل",
    downloadWord: "تحميل ملف Word",
    noAttachment: "لا يوجد ملف مرفق",
    submittedAt: "تاريخ الإرسال:",
    abstractLabel: "الملخص:",
    phoneLabel: "الهاتف:",
    deleteRequest: "حذف الطلب",
    confirmDeleteRequest: "هل تريد حذف هذا الطلب نهائياً؟ لا يمكن التراجع.",
    confirmRejectWithRefund:
      "سيتم رفض الطلب وإصدار استرداد كامل للمبلغ المدفوع إلى المؤلف عبر PayPal. هل تريد المتابعة؟",
    sendEmail: "إرسال بريد",
    refundOk: "تم الرفض وإصدار الاسترداد.",
    refundFailed: "تم الرفض لكن فشل الاسترداد — راجع صفحة المعاملات.",
  },

  publicationFeePage: {
    title: "رسوم نشر الدراسة",
    explainer: "حدّد رسوم نشر الدراسة الواحدة (ليست لكل مجلة). عند التفعيل يدفع المؤلف بعد إرسال الدراسة.",
    amountLabel: "المبلغ",
    currencyLabel: "العملة",
    enabledLabel: "تفعيل رسوم النشر",
    labelAr: "وصف عربي (اختياري)",
    labelEn: "وصف إنجليزي (اختياري)",
    save: "حفظ الإعدادات",
    saving: "جاري الحفظ…",
    saved: "تم حفظ الإعدادات.",
  },

  transactionsPage: {
    title: "سجل المعاملات",
    explainer: "عرض مدفوعات PayPal المرتبطة بطلبات النشر، إرسال بريد للمؤلف، وإعادة محاولة الاسترداد.",
    empty: "لا توجد معاملات.",
    searchPlaceholder: "بحث بالبريد أو عنوان الدراسة",
    filterAll: "كل الحالات",
    statusPending: "قيد الانتظار",
    statusCompleted: "مكتمل",
    statusFailed: "فشل",
    statusRefunded: "مسترد",
    statusCancelled: "ملغى",
    sendEmail: "إرسال بريد",
    retryRefund: "إعادة الاسترداد",
    emailSubject: "الموضوع",
    emailBody: "نص الرسالة",
    emailSend: "إرسال",
    emailSending: "جاري الإرسال…",
    colDate: "التاريخ",
    colAmount: "المبلغ",
    colStatus: "الحالة",
    colStudy: "الدراسة",
    colAuthor: "المؤلف",
    refundError: "خطأ الاسترداد:",
  },

  emailsPage: {
    title: "مركز البريد",
    explainer: "أرسل رسائل تشغيلية لمستخدمين أو جهات محددة، وراجع حالة الإرسال والأخطاء في السجل.",
    composeExplainer: "أرسل رسالة تشغيلية واحدة، ثم راجع النتيجة في السجل أدناه.",
    logsExplainer: "آخر عمليات الإرسال وحالتها.",
    placeholderTo: "البريد المستلم",
    placeholderSubject: "الموضوع",
    placeholderBody: "نص الرسالة",
    send: "إرسال",
    sending: "جاري الإرسال…",
    logsTitle: "سجل البريد",
    refreshLogs: "تحديث السجل",
    emptyLogs: "لا توجد سجلات بريد بعد.",
    errorPrefix: "خطأ:",
  },

  contentPage: {
    title: "المحتوى",
    explainer:
      "إدارة المدونات والمؤتمرات والمجالات العلمية الظاهرة في أقسام الموقع؛ كل كتلة لها نموذج إنشاء ثم قائمة للتعديل أو الحذف.",
    confirmDelete: "حذف هذا العنصر؟",
    blogSectionExplainer: "مقالات أو أخبار قصيرة مع صورة غلاف اختيارية.",
    conferenceSectionExplainer: "فعاليات مع التاريخ والمكان وعدد الحضور إن وجد.",
    fieldSectionExplainer: "مجالات أو تخصصات تُستخدم في التصنيف والعرض.",
    blogCreate: "تدوينة جديدة",
    blogEdit: "تعديل التدوينة",
    conferenceCreate: "مؤتمر جديد",
    conferenceEdit: "تعديل المؤتمر",
    fieldCreate: "مجال جديد",
    fieldEdit: "تعديل المجال",
    placeholderTitle: "العنوان",
    placeholderSummary: "الملخص",
    placeholderDate: "التاريخ",
    placeholderAuthor: "المؤلف",
    placeholderDescription: "الوصف",
    placeholderLocation: "المكان",
    placeholderAttendees: "الحضور أو العدد",
    placeholderFieldName: "اسم المجال",
    blogImageHint:
      "صورة الغلاف اختيارية: ارفع ملفًا أدناه أو افتح الرابط الحالي ثم استبدل بالرفع.",
    blogImageReplace: "صورة الغلاف الحالية:",
    conferenceImageReplace: "صورة الفعالية الحالية:",
    optionalCover: "صورة الغلاف اختيارية — ارفع ملفًا أدناه.",
    optionalImage: "صورة اختيارية — ارفع ملفًا أدناه.",
    submitBlogCreate: "إنشاء التدوينة",
    submitBlogUpdate: "تحديث التدوينة",
    submitConferenceCreate: "إنشاء المؤتمر",
    submitConferenceUpdate: "تحديث المؤتمر",
    submitFieldCreate: "إنشاء المجال",
    submitFieldUpdate: "تحديث المجال",
    openLink: "فتح",
    uploadBelowReplace: "— ارفع أدناه للاستبدال.",
  },

  trafficPage: {
    metaTitle: "تحليلات زيارات المجلات",
    metaDescription: "عرض إحصاءات مشاهدات وتفاعلات المجلات",
  },

  trafficDashboard: {
    title: "لوحة زيارات المجلات",
    explainer: "راقب المشاهدات والتحميلات والمشاركات، وقم بتصفية النتائج بفترة زمنية.",
    startDate: "من تاريخ:",
    endDate: "إلى تاريخ:",
    applyFilter: "تطبيق التصفية",
    loading: "جاري تحميل بيانات الزيارات…",
    colMagazine: "المجلة",
    colViews: "المشاهدات",
    colDownloads: "التحميلات",
    colShares: "المشاركات",
    colTotal: "إجمالي التفاعلات",
    emptyRange: "لا توجد بيانات زيارات لهذا النطاق.",
  },

  accountPage: {
    title: "أمان الحساب",
    explainer: "غيّر كلمة مرور الدخول إلى لوحة التحكم؛ بعد التحديث يُفضّل إعادة تسجيل الدخول.",
    placeholderCurrent: "كلمة المرور الحالية",
    placeholderNew: "كلمة المرور الجديدة (8 أحرف على الأقل)",
    submit: "تغيير كلمة المرور",
    updating: "جاري التحديث…",
    success: "تم تحديث كلمة المرور. يُفضّل تسجيل الدخول مجددًا.",
  },

  magazineAdvisorsPage: {
    title: "مستشارو المجلة",
    explainer:
      "أضف مستخدمين من القائمة العامة أو أنشئ صفًا خاصًا بهذه المجلة مع صورة ومنصب؛ يظهر ذلك على صفحة المجلة العامة.",
    sectionPickExplainer: "اختر مستشارًا مسجّلًا في النظام لإضافته بسرعة بنفس الصورة والاسم العام.",
    pickTitle: "اختيار من قائمة المستشارين",
    selectAdvisor: "اختر مستشارًا",
    addSelected: "إضافة المستشار المحدد",
    currentTitle: "المستشارون الحاليون",
    listExplainer: "المستشارون المعروضون على صفحة هذه المجلة العامة.",
    empty: "لا يوجد مستشارون بعد.",
    confirmRemove: "إزالة هذا المستشار؟",
    formExplainer: "أدخل الاسم والمنصب وصورة؛ مطلوب عند الإنشاء أو عند الاستبدال.",
    editAdvisor: "تعديل مستشار",
    addAdvisor: "إضافة مستشار",
    placeholderName: "الاسم",
    placeholderJob: "المسمّى أو الانتماء",
    photoHintEdit: "الصورة الحالية:",
    photoReplaceHint: "— ارفع ملفًا جديدًا أدناه للاستبدال.",
    photoRequiredNew: "الصورة مطلوبة: اختر ملفًا أدناه.",
    photoNoneEdit: "لا توجد صورة؛ ارفع واحدة أدناه.",
    submitAddAdvisor: "إضافة المستشار",
    submitUpdateAdvisor: "تحديث المستشار",
    invalidIdPage: "معرّف المجلة غير صالح.",
    loadingMagazine: "جاري التحميل…",
  },

  publishingConditionsPage: {
    title: "شروط النشر",
    explainer:
      "عرّف تبويبات المحتوى (العناوين والنصوص والأيقونات وترتيب العرض) التي يراها الزوار على صفحة شروط النشر للمجلة.",
    publicExplainer: "رابط المعاينة للصفحة العامة:",
    tabsListExplainer: "التبويبات المعروضة للزوار؛ عدّل أو احذف أو أعد الترتيب من النموذج أدناه.",
    currentTabsTitle: "التبويبات الحالية",
    emptyTabs: "لا توجد تبويبات بعد — أضف الأول من النموذج أدناه.",
    iconMeta: (labelAr: string, key: string) => `${labelAr} (${key})`,
    confirmDelete: "حذف تبويب شرط النشر هذا؟",
    formExplainer:
      "أدخل عنوانًا ونصًا بالعربية، واختر أيقونة تعبيرية ورقم ترتيب (الأصغر يظهر أولًا).",
    editTab: "تعديل التبويب",
    addTab: "تبويب جديد",
    placeholderTabTitle: "عنوان التبويب (عربي، مثل: شروط المؤلف)",
    placeholderTabBody:
      "محتوى التبويب (عربي). افصل بين الفقرات بسطر فارغ.",
    placeholderSort: "ترتيب العرض (0 = الأول)",
    submitAdd: "إضافة التبويب",
    submitUpdate: "تحديث التبويب",
    submitWorking: "جاري المعالجة…",
  },

  researchEditor: {
    sectionPickerExplainer: "حدّد مجلة ثم إصدارًا لعرض البحوث المرتبطة وتعديلها.",
    title: "بحوث المجلة",
    pickerHint: "اختر مجلةً وإصدارًا، ثم أضف بحوثًا أو حرّر القائمة.",
    selectMagazine: "اختر المجلة",
    selectMagazineFirst: "اختر مجلةً أولًا",
    noVersions: "لا توجد إصدارات لهذه المجلة",
    selectVersion: "اختر الإصدار",
    researchesForVersion: (vid: number, magTitle?: string) =>
      magTitle ? `بحوث الإصدار #${vid} (${magTitle})` : `بحوث الإصدار #${vid}`,
    publicHub: "صفحة الإصدار العامة:",
    openVersionPage: "فتح صفحة الإصدار",
    formHint:
      "للتحرير: اضغط «تعديل» على صف بحث لتحميله في النموذج، عدّل الحقول ثم «تحديث البحث». استخدم «إلغاء التحرير» لمسح النموذج دون حفظ.",
    placeholderResearchers: "أسماء الباحثين (مفصولة بفواصل)",
    placeholderResearchTitle: "عنوان البحث",
    placeholderUrl: "رابط صفحة البحث الخارجية",
    placeholderSummary: "ملخص (اختياري، يظهر على الموقع)",
    placeholderKeywords: "كلمات مفتاحية (مفصولة بفواصل، تظهر كوسوم)",
    pdfNone: "لا يوجد ملف PDF (اختياري).",
    pdfCurrent: "ملف PDF الحالي:",
    placeholderSort: "ترتيب العرض",
    addResearch: "إضافة بحث",
    updateResearch: "تحديث البحث",
    confirmDelete: "حذف هذا البحث؟",
  },
} as const;
